version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bytes
    versions:
    - "> 0.5.6, < 1"
  - dependency-name: bytes
    versions:
    - ">= 0.6.a, < 0.7"
  - dependency-name: tokio
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: tokio-util
    versions:
    - ">= 0.4.a, < 0.5"
  - dependency-name: tokio-util
    versions:
    - ">= 0.5.a, < 0.6"
  - dependency-name: hyper
    versions:
    - 0.14.2
    - 0.14.6
  - dependency-name: futures-util
    versions:
    - 0.3.14
  - dependency-name: once_cell
    versions:
    - 1.6.0
  - dependency-name: tokio-util
    versions:
    - 0.6.2
    - 0.6.3
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: bytes
    versions:
    - 1.0.1
  - dependency-name: rusoto_signature
    versions:
    - 0.46.0
  - dependency-name: rusoto_core
    versions:
    - 0.46.0
  - dependency-name: rusoto_s3
    versions:
    - 0.46.0
  - dependency-name: rusoto_credential
    versions:
    - 0.46.0
  - dependency-name: hyper-tls
    versions:
    - 0.5.0
  - dependency-name: hyper-rustls
    versions:
    - 0.22.1
