[config]
default_to_workspace = false

[env]
BUILD_FLAVOR = ""
TLS_PROVIDER = "rustls"
TARGET = ""
WORKSPACE = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.release]
BUILD_FLAVOR = "--release"

[env.'release+static']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-unknown-linux-musl"

[env.'release+nativetls']
BUILD_FLAVOR = "--release"
TLS_PROVIDER = "nativetls"

[tasks.check]
command = "cargo"
args = [
        "check",
        "--features=${TLS_PROVIDER},blocking",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.lint]
command = "cargo"
args = ["clippy", "--no-default-features", "--features=${TLS_PROVIDER},aggressive_lint,blocking"]

[tasks.build]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.build-min-cli]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.build-lib]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.test]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "--nocapture"
        ]

[tasks.test-min]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "--nocapture"
        ]
