[config]
default_to_workspace = false

[env]
BUILD_FLAVOR = ""
VERBOSE = ""
TLS_PROVIDER = "rustls"
TARGET = ""
WORKSPACE = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.release]
BUILD_FLAVOR = "--release"
RUSTFLAGS="-C link-arg=-fuse-ld=lld -C codegen-units=1 -C panic=abort"
VERBOSE = "-vv"

[env.'release+static']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-unknown-linux-musl"
RUSTFLAGS="-C link-arg=-fuse-ld=lld -C codegen-units=1 -C panic=abort"
VERBOSE = "-vv"

[env.'release+mac']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-apple-darwin"
RUSTFLAGS="-C link-arg=-fuse-ld=lld -C codegen-units=1 -C panic=abort"
VERBOSE = "-vv"

[env.'release+windows']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-pc-windows-msvc -C panic=abort"

[env.'release+nativetls']
BUILD_FLAVOR = "--release"
TLS_PROVIDER = "nativetls"
RUSTFLAGS="-C link-arg=-fuse-ld=lld -C codegen-units=1 -C panic=abort"
VERBOSE = "-vv"

[env.'dev+nativetls']
TLS_PROVIDER = "nativetls"
VERBOSE = "-vv"

[tasks.check]
command = "cargo"
args = [
        "check",
        "--features=${TLS_PROVIDER},blocking",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.lint]
command = "cargo"
args = ["clippy", "--no-default-features", "--features=${TLS_PROVIDER},aggressive_lint,blocking"]

[tasks.build]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(VERBOSE)",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.build-min-cli]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.build-lib]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.test]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "${@}",
        "--features=${TLS_PROVIDER}",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "@@remove-empty(TEST_FILTER)",
        "--nocapture"
        ]

[tasks.test-min]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "@@remove-empty(TEST_FILTER)",
        "--nocapture"
        ]
