[config]
default_to_workspace = false

[env]
BUILD_FLAVOR = ""
TLS_PROVIDER = "rustls"
TARGET = ""

[env.release]
BUILD_FLAVOR = "--release"

[env.'release+static']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-unknown-linux-musl"

[env.'release+nativetls']
BUILD_FLAVOR = "--release"
TLS_PROVIDER = "nativetls"

[tasks.check]
command = "cargo"
args = [
        "check",
        "--features=${TLS_PROVIDER},blocking,cli,compression,http_server",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]
cwd = "src/esthri"

[tasks.build]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},blocking,cli,compression,http_server",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]
cwd = "src/esthri"

[tasks.build-min-cli]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint,cli",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]
cwd = "src/esthri"

[tasks.build-lib]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]
cwd = "src/esthri"

[tasks.test]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
cwd = "src/esthri"
command = "cargo"
args = [
        "test",
        "--features=${TLS_PROVIDER},blocking,cli,compression,http_server",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "--nocapture"
        ]

[tasks.lint]
command = "cargo"
cwd = "src/esthri"
args = ["clippy", "--no-default-features", "--features=${TLS_PROVIDER},aggressive_lint,blocking,cli,compression,http_server"]
