[config]
default_to_workspace = false

[env]
BUILD_FLAVOR = ""
VERBOSE = ""
TLS_PROVIDER = "rustls"
TARGET = ""
WORKSPACE = "${CARGO_MAKE_WORKING_DIRECTORY}"
MSRV = ""

[env.release]
BUILD_FLAVOR = "--release"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
VERBOSE = "-vv"

[env.'release+static']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-unknown-linux-musl"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
VERBOSE = "-vv"

[env.'release+static+aarch64']
CC_aarch64_unknown_linux_musl="clang"
AR_aarch64_unknown_linux_musl="llvm-ar"
CFLAGS_aarch64_unknown_linux_musl="-I/usr/aarch64-linux-gnu/include"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER="qemu-aarch64 -L /usr/aarch64-linux-gnu"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-C link-self-contained=yes -C linker=rust-lld -C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
BUILD_FLAVOR = "--release"
TARGET = "--target=aarch64-unknown-linux-musl"
VERBOSE = "-vv"

[env.'dev+static+aarch64']
CC_aarch64_unknown_linux_musl="clang"
AR_aarch64_unknown_linux_musl="llvm-ar"
CFLAGS_aarch64_unknown_linux_musl="-I/usr/aarch64-linux-gnu/include"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER="qemu-aarch64 -L /usr/aarch64-linux-gnu"
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-C link-self-contained=yes -C linker=rust-lld"
TARGET = "--target=aarch64-unknown-linux-musl"
VERBOSE = "-vv"

[env.'release+mac']
BUILD_FLAVOR = "--release"
TARGET = "--target=x86_64-apple-darwin"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
VERBOSE = "-vv"

[env.'dev+mac']
TARGET = "--target=x86_64-apple-darwin"
VERBOSE = "-vv"

[env.'release+mac+aarch64']
BUILD_FLAVOR = "--release"
TARGET = "--target=aarch64-apple-darwin"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
VERBOSE = "-vv"

[env.'dev+mac+aarch64']
TARGET = "--target=aarch64-apple-darwin"
VERBOSE = "-vv"

[env.'release+windows']
BUILD_FLAVOR = "--release"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
TARGET = "--target=x86_64-pc-windows-msvc"
VERBOSE = "-vv"

[env.'dev+windows']
TARGET = "--target=x86_64-pc-windows-msvc"
VERBOSE = "-vv"

[env.'release+nativetls']
BUILD_FLAVOR = "--release"
TLS_PROVIDER = "nativetls"
RUSTFLAGS="-C codegen-units=1 -C panic=abort -C lto=fat -C opt-level=3"
VERBOSE = "-vv"

[env.'dev+nativetls']
TLS_PROVIDER = "nativetls"
VERBOSE = "-vv"

[env.'dev+msrv']
MSRV = "+1.72.0"
VERBOSE = "-vv"

[env.'dev+msrv+nativetls']
TLS_PROVIDER = "nativetls"
MSRV = "+1.72.0"
VERBOSE = "-vv"

[tasks.check]
command = "cargo"
args = [
        "check",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.lint]
command = "cargo"
args = ["clippy", "--no-default-features", "--features=${TLS_PROVIDER},aggressive_lint,blocking"]

[tasks.build]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(VERBOSE)",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)"
        ]

[tasks.do-cargo]
private = true
install_crate = false
command = "cargo"
args = [
        "@@remove-empty(MSRV)",
        "${CARGO_SUBCOMMAND}",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)",
        "@@split(PACKAGE, )",
        ]

[tasks.build-cli]
command = "cargo"
args = [
        "build",
        "--features=${TLS_PROVIDER},aggressive_lint",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "@@remove-empty(TARGET)",
        "-p", "esthri-cli",
        ]

[tasks.build-lib]
run_task = "do-cargo"
env = { PACKAGE="-p esthri", CARGO_SUBCOMMAND = "build" }

[tasks.check-lib]
run_task = "do-cargo"
env = { PACKAGE="-p esthri", CARGO_SUBCOMMAND = "check" }

[tasks.test]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "${@}",
        "--features=${TLS_PROVIDER}",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "@@remove-empty(TEST_FILTER)",
        "--nocapture"
        ]

[tasks.test-min]
env = { RUST_LOG = "esthri=debug", RUST_BACKTRACE = "1" }
command = "cargo"
args = [
        "test",
        "--features=${TLS_PROVIDER},blocking",
        "--no-default-features",
        "@@remove-empty(BUILD_FLAVOR)",
        "--",
        "@@remove-empty(TEST_FILTER)",
        "--nocapture"
        ]
