post-release-commit-message = "Start next development iteration: {{next_version}}"
pre-release-commit-message = "release: {{crate_name}}: version {{version}}"
tag-message = "Esthri version {{tag_name}}"
tag-name = "{{version}}"
allow-branch = ["master"]
consolidate-commits = false
consolidate-pushes = true
