pre-release-commit-message = "Release: {{version}}"
post-release-commit-message = "Start next development iteration: {{next_version}}"
tag-message = "{{tag_name}}"
tag-name = "{{version}}"
allow-branch = ["master"]
