# This is a basic workflow to help you get started with Actions

name: Build macOS and Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ adrian/publish ]
  #      tags:
  #        - '[0-9]+.[0-9]+.[0-9]+*'
  #        - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-10.15
            profile: release+mac
            target: x86_64-apple-darwin
          - os: macos-11
            profile: release+m1
            target: aarch64-apple-darwin
          - os: windows-2019
            profile: release+windows
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-${{ matrix.target }}
          profile: minimal

      - name: Build
        shell: bash
        run: |
          rustup target add ${{ matrix.target }}
          cargo make --profile ${{ matrix.profile }} build
          ls target/${{ matrix.target }}/release

#      - name: Package Release
#        shell: bash
#        run: |
#          touch LICENSE.txt
#          cargo make zip-release-binary-for-target \
#            --no-workspace \
#            --env CARGO_MAKE_BINARY_EXECUTABLE_NAME=esthri \
#            --env CARGO_MAKE_RELEASE_FLOW_TARGET=${{ matrix.binary_target }} \
#            --env CARGO_MAKE_PROJECT_NAME=esthri \
#            --env CARGO_MAKE_PROJECT_VERSION=${{ steps.get_tag.outputs.tag }}

      - name: Upload Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "target/${{ matrix.target }}/release/esthri"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true