# This is a basic workflow to help you get started with Actions

name: Build macOS and Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-10.15
            profile: release+mac
            target: x86_64-apple-darwin
          - os: macos-11
            profile: release+m1
            target: aarch64-apple-darwin
          - os: windows-2019
            profile: release+windows
            target: x86_64-pc-windows-msvc
            suffix: .exe

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Store git tag vars
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-${{ matrix.target }}
          profile: minimal

      - name: Build
        shell: bash
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --all-features --target ${{ matrix.target }}

      - name: Package release
        shell: bash
        run: |
          tar -C target/${{ matrix.target }}/release -czf esthri-${{ env.VERSION }}-${{ matrix.target }}.tar.gz esthri${{ matrix.suffix }}

      - name: Upload Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.tar.gz"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true